package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"backend/services/graph/model"
	"backend/services/services"
	"context"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	return db.CreateProject(input), nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input model.UpdateProjectInput) (*model.Project, error) {
	return db.UpdateProject(id, input), nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (*model.DeleteProjectResponse, error) {
	return db.DeleteProject(id), nil
}

// Getallprojects is the resolver for the getallprojects field.
func (r *queryResolver) Getallprojects(ctx context.Context) ([]*model.Project, error) {
	return db.GetAllProjects(), nil
}

// Getproject is the resolver for the getproject field.
func (r *queryResolver) Getproject(ctx context.Context, id string) (*model.Project, error) {
	return db.GetProject(id), nil
}

// Getprojectsbyworkspace is the resolver for the getprojectsbyworkspace field.
func (r *queryResolver) Getprojectsbyworkspace(ctx context.Context, workspaceid string) ([]*model.Project, error) {
	return db.GetProjectsByWorkspace(workspaceid), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var db = services.Connect()
