// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Credentials struct {
	ID           string   `json:"_id"`
	Username     string   `json:"username"`
	Botusertoken string   `json:"botusertoken"`
	Channelid    []string `json:"channelid"`
}
