// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProjectInput struct {
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Owner         string    `json:"owner"`
	Status        *string   `json:"status"`
	Createdat     string    `json:"createdat"`
	Workspaceid   string    `json:"workspaceid"`
	Token         *string   `json:"token"`
	Collaborators []*string `json:"collaborators"`
}

type CreateWorkspaceInput struct {
	Name     string `json:"name"`
	Username string `json:"username"`
}

type DeleteProjectResponse struct {
	DeletedProjectID string `json:"deletedProjectId"`
}

type DeleteWorkspaceResponse struct {
	DeletedWorkspaceID string `json:"deletedWorkspaceId"`
}

type Project struct {
	ID            string    `json:"_id" bson:"_id"`
	Name          string    `json:"name"`
	Owner         string    `json:"owner"`
	Createdat     string    `json:"createdat"`
	Status        *string   `json:"status"`
	Description   string    `json:"description"`
	Workspaceid   string    `json:"workspaceid"`
	Token         *string   `json:"token"`
	Collaborators []*string `json:"collaborators"`
}

type UpdateProjectInput struct {
	Name          *string   `json:"name"`
	Description   *string   `json:"description"`
	Status        *string   `json:"status"`
	Workspaceid   *string   `json:"workspaceid"`
	Token         *string   `json:"token"`
	Collaborators []*string `json:"collaborators"`
}

type UpdateWorkspaceInput struct {
	Name *string `json:"name"`
}

type Workspace struct {
	ID       string `json:"_id" bson:"_id"`
	Name     string `json:"name"`
	Username string `json:"username"`
}
