// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
}

type CreateProjectInput struct {
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Workspaceid   string    `json:"workspaceid"`
	Token         *string   `json:"token"`
	Collaborators []*string `json:"collaborators"`
}

type CreateWorkspaceInput struct {
	Name     string `json:"name"`
	Username string `json:"username"`
}

type DeleteJobResponse struct {
	DeletedJobID string `json:"deletedJobId"`
}

type DeleteProjectResponse struct {
	DeletedProjectID string `json:"deletedProjectId"`
}

type DeleteWorkspaceResponse struct {
	DeletedWorkspaceID string `json:"deletedWorkspaceId"`
}

type JobListing struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
}

type Project struct {
	ID            string    `json:"_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Workspaceid   string    `json:"workspaceid"`
	Token         *string   `json:"token"`
	Collaborators []*string `json:"collaborators"`
}

type UpdateJobListingInput struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	URL         *string `json:"url"`
}

type UpdateProjectInput struct {
	Name          *string   `json:"name"`
	Description   *string   `json:"description"`
	Workspaceid   *string   `json:"workspaceid"`
	Token         *string   `json:"token"`
	Collaborators []*string `json:"collaborators"`
}

type UpdateWorkspaceInput struct {
	Name *string `json:"name"`
}

type Workspace struct {
	ID       string `json:"_id"`
	Name     string `json:"name"`
	Username string `json:"username"`
}
