version: '3.3'
services:
  gol:
    container_name: 'go-container'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
    environment: 
      - MONGO_URI=mongodb://localhost:27017
