version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - "node_modules:/app/node_modules"

volumes:
  node_modules:
